version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    networks:
      - opentraffic_datastore
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    networks:
      - opentraffic_datastore
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #these topics map directly to those in the kafka application
      KAFKA_CREATE_TOPICS: "frontend:1:1,backend:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  datastore_frontend:
    image: opentraffic/datastore_frontend:latest
    networks:
      - opentraffic_datastore
    ports:
      - "8003:8003"
    command:
      bash -c "sleep 30 && /usr/local/bin/opentraffic-datastore-frontend -l :8003 -b 172.17.0.1:9092 -t frontend"

  datastore_accumulator:
    image: opentraffic/datastore_accumulator:latest
    networks:
      - opentraffic_datastore
    command:
      bash -c "sleep 30 && java -cp /datastore/build/libs/datastore_accumulator-all-1.0-SNAPSHOT.jar io.opentraffic.datastore.Accumulator -b 172.17.0.1:9092 -i frontend -o backend --verbose"


networks:
  opentraffic_datastore:
    driver: bridge
