version: '2'

services:
  postgres:
    image: postgres:9.6.1
    networks:
      - opentraffic_datastore
    ports:
      - "5432:5432"
    volumes:
      - ${PGDATA}:/data
    environment:
      - POSTGRES_USER=opentraffic
      - POSTGRES_DB=opentraffic
      - POSTGRES_PASSWORD=changeme
      - PGDATA=/data/postgres

networks:
  opentraffic_datastore:
    driver: bridge
